name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create env file
        run: |
          touch lib/conf.ts
          echo "Saving export const HOST_DNS = 'http://${{ secrets.HOST_DNS }}' to lib/conf.ts"
          echo "export const HOST_DNS = 'http://${{ secrets.HOST_DNS }}'" > lib/conf.ts
          cat lib/conf.ts

      - name: Install npm dependencies
        run: npm install

      - name: Run build task
        run: npm run build --if-present

      - name: Install PM2
        run: npm install pm2 -g

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rlgoDzvc -i --delete'
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: '/node_modules/'

      - name: PM2 restart
        run: |
          touch key.pem
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
          ssh -i key.pem ${{secrets.USERNAME}}@${{secrets.HOST_DNS}} -p 22 '
          cd /home/ec2-user/shorts/
          npm i
          nohup sudo npm start > npm_start.log 2>&1 &
          '
